#!/bin/tcsh
#
# STOP-LISP
#
# Stop all LISP processes and remove the named socket descriptors and any
# iptables rules created by lispers.net. 
#
#------------------------------------------------------------------------------

ls lisp-itr >& /dev/null
set itr = $status

set pids = `./pslisp | egrep python | cut -f 1 -d " "`
echo "Stopping LISP processes [$pids] ..."
foreach p ($pids)
    sudo kill $p
end

#
# Remove LISP lock files.
#
python remove-lisp-locks.pyo

#
# User created iptables rules and doesn't want lispers.net to remove anything.
#
if ($?LISP_NO_IPTABLES) then
    echo "User bypass removing LISP iptables"
    exit(0)
endif

#
# Remove iptables lispers.net created if we are an ITR.
#
if ($itr == 0) then
    python remove-lisp-iptables.pyo
else
    echo "Bypass removing LISP iptables, ITR process not running"
endif
exit(0)

#------------------------------------------------------------------------------
